//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace asset_proof_of_concept_demo_CSharp
{
    using System;

    [Obsolete("Using embedded XML Version and Dependencies")]
    public interface IVersionAndDependencies
    {
        #region Methods

        String VersionAndDependenciesXml(Type Class);

        #endregion Methods
    }
}